# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 30
Set Width 1200
Set Height 700

# Type a command in the terminal.
Type "go run ../."
Enter

Sleep 1s
Right
Sleep 1s
Left
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right

Sleep 1s
Type "i"

Sleep 1s
Right

Sleep 1s
Type "i"
Sleep 500ms
Type "i"

Sleep 1s
Right

Sleep 1s
Type "i"
Sleep 500ms
Type "i"
Sleep 500ms
Type "i"

Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Right







Sleep 2s
Type "q"